export { default as NavBar } from "./NavBar";
export { default as Button } from "./Button";
export { default as Content } from "./Content";
export { default as Contacts } from "./Contacts";
export { default as Skills } from "./Skills";
export { default as Resume } from "./Resume";
export { default as Projects } from "./Projects";
export { default as UpButton } from "./UpButton";
export { default as Footer } from "./Footer";
